### ISSUE TITLE
VSCode Interactive Console does not work with Robotframework 7.0.0

### ISSUE THREAD

**Issue by ka98** [robocorp/robotframework-lsp#1085]
**Describe the bug**
If I execute "Log To Console    message" the interactive Shell reports an error:

Error'_ExecutionContext' object has no attribute 'body' [-]
Traceback (most recent call last):
  File "/home/user/.vscode/extensions/robocorp.robotframework-lsp-1.13.0/src/robotframework_ls/vendored/robotframework_interactive/interpreter.py", line 422, in evaluate
    return self._evaluate(code)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.vscode/extensions/robocorp.robotframework-lsp-1.13.0/src/robotframework_ls/vendored/robotframework_interactive/interpreter.py", line 532, in _evaluate
    last_result = facade.run_test_body(context, test, model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.vscode/extensions/robocorp.robotframework-lsp-1.13.0/src/robotframework_ls/vendored/robotframework_interactive/robotfacade.py", line 120, in run_test_body
    ret = step.run(context, True, False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/cvc-blu-sw/venv/lib/python3.12/site-packages/robot/running/model.py", line 144, in run
    return KeywordRunner(context, run).run(self, result.body.create_keyword())
                                                 ^^^^^^^^^^^
AttributeError: '_ExecutionContext' object has no attribute 'body'

**To Reproduce**
Install Robotframework with at least 7.0 Version
Install newest Version of "Robot Framework Language Server" (at the time of writing this was v1.13.0)
Start an Interactive Shell and input "Log To Console    message"

This issue does not occur with Robot Framework version 6.1.1

**Expected behavior**
The shell should return "message" not return an error

**Screenshots**
![image](https://github.com/user-attachments/assets/15f9db18-291d-4da8-bb73-eb057e73a208)

**Workaround**
Downgrade robotframework version 6.1.1 

**Versions:**
 - OS: Linux Arch Kernel Version 6.11.5-arch1-1
 - Robot Framework Version: I tested with 7.0 and 7.1.1
 - Robot Framework Language Server Version: robotframework-lsp-1.13.0
 - Client Version: VSCode: 1.95.0
 - Python: 3.12.7

VSCode:
Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.11.5-arch1-1

**Comment by fabioz** [comment]
Closing as this is related to RF 7.

See: https://github.com/robocorp/robotframework-lsp/issues/1051 for details (PRs welcome).
